version: "1"
services:
  mongo-container-social-app:
    image: mongo:latest
    container_name: "mongo-container-social-app"
    ports:
      - 28000:27017
  social-media-app:
    image: wwx2/social-media-app
    container_name: "social-media-app"
    ports:
      - 8093:8080
    links:
      - mongo-container-social-app
